<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Login</title>
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <h1>Login</h1>
        <form method="POST" action="index.php?action=login"> 
            <label for="nombre">Nombre:</label>
            <input type="text" id="nombre" name="nombre" required>
            <br>
            <br>
            <label for="contraseña">Contraseña:</label>
            <input type="password" id="contraseña" name="contraseña" required>
            <br>
            <br>
            <input type="submit" value="Iniciar sesión">
        </form>
    </body>
</html>
