<?php
    require_once 'db.php';
?>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Main View</title>
    </head>
    <body>
        <?php 
        if (!isset($_GET['action']) || $_GET['action'] !== 'register') {
            require_once 'loginView.phtml';
            $registrarse = '<a href="index.php?action=register"><button>Registrarse</button></a>';
            echo '<br>';
            echo '<label for="nombre">No tienes sesion creada?, creala  </label>';
            echo '<br>';
            echo '<br>';
            echo $registrarse;
        }
        ?>
        
    </body>
    

