<?php
    require_once 'db.php';
?>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Tienda Online</title>
        <link rel="stylesheet" href="css/styles.css">
    </head>
    <body>
        <nav>
            <?php if (isset($_SESSION['user_id'])): ?>
                <span>Hola, <?= htmlspecialchars($_SESSION['user_nombre']) ?></span>
                <a href="index.php?action=logout"><button>Logout</button></a>
                <a href="index.php?c=order&show=1" class="nav-right"><button>Ver Carrito</button></a>
            <?php else: ?>
                <h1>Tienda Online</h1>
                <a href="index.php?action=login"><button>Iniciar sesión</button></a>
                <a href="index.php?action=register"><button>Registrarse</button></a>
            <?php endif; ?>
        </nav>
        <?php if (isset($_SESSION['user_id'])): ?>
            <div class="productos-center-container">
                <h2>Productos disponibles:</h2>
                <a href="index.php?action=productos&view=1"><button class="btn-large">Ver Productos</button></a>
            </div>
        <?php endif; ?>
    </body>
</html>
