<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Productos</title>
    </head>
    <body>
        <form action="index.php?action=productos&view=1" method="POST"></form>
        <h1>Productos</h1>
        <a href="index.php?action=productos&new=1"><button>Nuevo Producto</button></a>
        <a href="index.php?action=index"><button>Volver</button></a>
        <?php foreach ($products as $product): ?>
            <div>
                <h3><?= htmlspecialchars($product['nombre']) ?></h3>
                <p><?= htmlspecialchars($product['descripcion']) ?></p>
                <p>Precio: <?= htmlspecialchars($product['precio']) ?>€</p>
                <p>Stock: <?= htmlspecialchars($product['stock']) ?></p>
            </div>
        <?php endforeach; ?>
    </body>
</html>
